export type { BeaconPosition, SpotlightBeaconProps } from './spotlight-beacon.tsx'
export { SpotlightBeacon } from './spotlight-beacon.tsx'
export type { SpotlightHighlightProps } from './spotlight-highlight.tsx'
export { SpotlightHighlight } from './spotlight-highlight.tsx'
export { SpotlightProvider } from './spotlight-provider.tsx'
export type { SpotlightTourProps } from './spotlight-tour.tsx'
export { SpotlightTour } from './spotlight-tour.tsx'
